In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [3]:
df = pd.read_csv('/kaggle/input/car-data/car data.csv')

In [4]:
df.sample(5)

     speed  car_age  experience  risk
101    169        1   12.345274    26
192    133       27    9.964954    83
276    130       26    6.656316    49
25     143       13    7.684037    77
19     128       15    1.508691    24

In [5]:
df.head()

   speed  car_age  experience  risk
0    172       22    8.104042    42
1     94       17   11.429461    36
2    186       20   14.819477    45
3    151       10   15.343897    38
4    100        6   16.455807    47

In [6]:
df.isnull().sum()

speed         0
car_age       0
experience    0
risk          0
dtype: int64

In [7]:
df.experience.mean()

10.124916517871657

In [8]:
df.experience.median()

10.582101444783259

In [19]:
from sklearn.linear_model import LinearRegression
import warnings
warnings.filterwarnings("ignore", message="X does not have valid feature names")

reg = linear_model.LinearRegression()

In [20]:
reg.fit(df[['speed','car_age','experience']], df.risk)

LinearRegression()

In [21]:
reg.predict([[160,10,9]])

array([53.8777018])

In [22]:
reg.coef_

array([-0.0302617 , -0.14473869, -0.27965041])

In [23]:
reg.intercept_

62.68381438116153

In [24]:
160*-0.0302617 + 10*-0.14473869 + 9*-0.27965041 + 62.68381438116153

53.877701791161535